<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../GscImporter.Domain/GscImporter.Domain.csproj" />
    <ProjectReference Include="../GscImporter.Application/GscImporter.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" />
  </ItemGroup>
</Project>
